version: '3.8'

services:
  mysql:
    image: mysql:8.2.0-oracle
    container_name: feedbacks_mysql
    environment:
      MYSQL_DATABASE: feedbacks_store
      MYSQL_ROOT_PASSWORD: feedbacks
    ports:
      - "3306:3306"

  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq
    environment:
      ARTEMIS_USER: mq
      ARTEMIS_PASSWORD: mq
    ports:
      - "61616:61616"
      - "8161:8161"
