services:
  mysql:
    image: mysql:8.2.0-oracle
    container_name: feedbacks_mysql
    environment:
      MYSQL_DATABASE: feedbacks_store
      MYSQL_ROOT_PASSWORD: feedbacks
    ports:
      - "3306:3306"
